export const TUTK_RECIPES = [
  {
    id: "B01",
    name: "SWEET EGG SCRAMBLE",
    category: "BREAKFAST",
    calories: 280,
    time: "10 MIN",
    protein: 30,
    fat: 4,
    carbs: 22,
    ingredients: ["3 egg whites", "\u00bd scoop vanilla protein powder", "2/3 cup frozen berries", "2 stevia packets", "\u00bc tsp vanilla extract", "Dash of cinnamon"],
    directions: ["\ud83c\udf73 PREP: Grease skillet with cooking spray and bring to medium heat.", "\ud83e\udd5a MIX: Whisk egg whites, protein powder, vanilla & cinnamon in a bowl.", "\ud83e\uded0 COOK: Pour onto skillet. Once halfway set, add berries and scramble until fully cooked."],
    scienceNote: "Egg whites deliver complete protein with minimal fat \u2014 ideal for 40+ metabolisms that need protein without the caloric load of whole eggs.",
    proTip: "Top with Walden Farms Pancake Syrup for extra sweetness without the sugar hit.",
    pillar: "FEAST" as const,
  },
  {
    id: "B02",
    name: "EGG WHITE OMELET",
    category: "BREAKFAST",
    calories: 260,
    time: "15 MIN",
    protein: 28,
    fat: 2,
    carbs: 30,
    ingredients: ["1\u00bc cup egg whites", "Handful of spinach (torn)", "2/3 cup raw chopped sweet potato", "Pico de gallo to taste", "Dash cinnamon", "2 stevia packets"],
    directions: ["\ud83c\udf60 POTATO: Poke holes in sweet potato, spray with PAM, microwave on potato setting.", "\ud83e\udd6c SAUT\u00c9: Bring greased skillet to medium heat. Saut\u00e9 spinach until wilted.", "\ud83e\udd5a FINISH: Add egg whites on top. Flip halfway. Top with pico de gallo."],
    scienceNote: "Sweet potato provides complex carbs with a low glycemic response, supporting stable energy levels \u2014 especially important for 40+ blood sugar management.",
    proTip: "Top sweet potato with cinnamon and stevia instead of butter \u2014 just as satisfying.",
    pillar: "FEAST" as const,
  },
  {
    id: "B03",
    name: "SAVORY TURKEY BAKE",
    category: "BREAKFAST",
    calories: 310,
    time: "20 MIN",
    protein: 34,
    fat: 8,
    carbs: 22,
    ingredients: ["3 oz cooked ground turkey", "3 egg whites", "1 cup finely chopped cauliflower/broccoli", "\u00bd cup oats", "Garlic salt to taste"],
    directions: ["\ud83e\udd63 MIX: Combine all ingredients in a medium mixing bowl and whisk thoroughly.", "\ud83e\uded9 PORTION: Pour evenly into 2\u20133 muffin tins or a single oven-safe dish.", "\ud83d\udd25 BAKE: Bake at 350\u00b0F for 8\u201310 minutes. Serve with hot sauce of choice."],
    scienceNote: "Combining eggs and turkey creates a complete amino acid profile that signals muscle protein synthesis \u2014 critical for maintaining lean mass after 40.",
    proTip: "Make a batch of 6 on Sunday \u2014 they refrigerate perfectly for a grab-and-go breakfast all week.",
    pillar: "FEAST" as const,
  },
  {
    id: "B04",
    name: "BLUEBERRY OVERNIGHT OATS",
    category: "BREAKFAST",
    calories: 295,
    time: "5 MIN + OVERNIGHT",
    protein: 24,
    fat: 3,
    carbs: 40,
    ingredients: ["1\u00bd cup fat-free Greek yogurt", "\u00bc cup oats", "\u00bc cup berries", "1 tsp vanilla extract", "2 stevia packets"],
    directions: ["\ud83e\udd63 LAYER: Mix Greek yogurt with vanilla & stevia. Microwave oats with water until cooked.", "\ud83e\uded9 JAR: Put oatmeal at the bottom of an overnight jar. Add frozen berries on top.", "\ud83c\udf19 SET: Top with Greek yogurt. Refrigerate overnight and grab in the morning."],
    scienceNote: "Greek yogurt's probiotics support gut health, which directly impacts nutrient absorption \u2014 a key factor as digestive efficiency naturally declines after 40.",
    proTip: "Add chia seeds for extra omega-3s and a thicker, more satisfying texture.",
    pillar: "FEAST" as const,
  },
  {
    id: "B05",
    name: "GUILT FREE FRENCH TOAST",
    category: "BREAKFAST",
    calories: 300,
    time: "15 MIN",
    protein: 28,
    fat: 4,
    carbs: 36,
    ingredients: ["3 slices Ezekiel bread", "1\u00bc cup egg whites", "1 tsp vanilla", "Dash of cinnamon", "Dash of salt"],
    directions: ["\ud83c\udf5e TOAST: Lightly toast Ezekiel bread in toaster oven.", "\ud83e\udd5a SOAK: Whisk egg whites with vanilla, cinnamon & salt. Soak bread slices in mixture.", "\ud83c\udf73 COOK: Cook soaked bread on greased skillet at medium heat. Flip until eggs are fully set."],
    scienceNote: "Ezekiel bread is made from sprouted grains which significantly reduces the glycemic response compared to regular bread \u2014 ideal for managing insulin sensitivity after 40.",
    proTip: "Top with Walden Farms Pancake Syrup \u2014 zero calories, zero sugar, full satisfaction.",
    pillar: "FEAST" as const,
  },
  {
    id: "B06",
    name: "EGG WHITE MCMUFFINS",
    category: "BREAKFAST",
    calories: 260,
    time: "20 MIN",
    protein: 26,
    fat: 5,
    carbs: 24,
    ingredients: ["1\u00bc cup egg whites", "1 leafy veggie of choice (cooked)", "1 solid veggie of choice (cooked)", "\u00bd cup oatmeal", "1 tsp baking powder", "Dash of salt"],
    directions: ["\ud83e\udd63 MIX: Combine all ingredients in a single bowl and mix thoroughly.", "\ud83e\uded9 POUR: Portion evenly into 2\u20133 greased muffin tins.", "\ud83d\udd25 BAKE: Bake at 350\u00b0F for 10\u201312 minutes until cooked through. Top with sauce of choice."],
    scienceNote: "Oats in this recipe provide beta-glucan fiber that supports cardiovascular health \u2014 particularly beneficial for 40+ adults managing cholesterol levels.",
    proTip: "Try spinach + diced peppers. These store in the fridge for 4 days \u2014 meal prep gold.",
    pillar: "FEAST" as const,
  },
  {
    id: "B07",
    name: "SAVORY BREAKFAST OATS",
    category: "BREAKFAST",
    calories: 340,
    time: "15 MIN",
    protein: 36,
    fat: 8,
    carbs: 28,
    ingredients: ["\u00bd cup oatmeal", "6 oz ground turkey", "1 handful spinach", "\u00bc cup water", "Balsamic vinegar to taste", "Garlic salt to taste"],
    directions: ["\ud83c\udf73 TURKEY: Grease skillet and bring to low-medium heat. Add ground turkey and cook halfway.", "\ud83c\udf3e OATS: Drizzle balsamic vinegar on turkey, then add oats and water. Cook until thick.", "\ud83e\udd6c FINISH: Add spinach, drizzle more balsamic. Remove from heat when spinach shrivels."],
    scienceNote: "Starting the day with both protein and complex carbs stabilizes cortisol levels \u2014 crucial for 40+ adults whose stress hormone regulation naturally becomes less efficient.",
    proTip: "This sounds unconventional but tastes incredible \u2014 think of it like a savory porridge bowl.",
    pillar: "FEAST" as const,
  },
  {
    id: "B08",
    name: "CAULIFLOWER BREAKFAST PIZZA",
    category: "BREAKFAST",
    calories: 270,
    time: "20 MIN",
    protein: 24,
    fat: 5,
    carbs: 28,
    ingredients: ["1 cup finely diced cauliflower", "1\u00bc cup egg whites", "\u00bd cup ground oats", "\u00bd small tomato, sliced", "Oregano and salt to taste"],
    directions: ["\ud83e\udd66 STEAM: Add \u00bc cup water to cauliflower and steam 5 minutes at medium power until soft.", "\ud83e\udd63 MIX: Combine cauliflower, ground oats, egg whites, oregano & salt in bowl.", "\ud83c\udf73 COOK: Pour on greased skillet, cover with lid for 4\u20135 min, flip and cook until firm."],
    scienceNote: "Cauliflower is rich in sulforaphane, a compound that supports the body's natural anti-inflammatory response \u2014 key for joint health after 40.",
    proTip: "Top with salsa or a drizzle of hot sauce for a full breakfast pizza experience.",
    pillar: "FEAST" as const,
  },
  {
    id: "B09",
    name: "BLUEBERRY CHEESECAKE BOWL",
    category: "BREAKFAST",
    calories: 250,
    time: "5 MIN",
    protein: 28,
    fat: 5,
    carbs: 22,
    ingredients: ["1 cup cottage cheese", "\u00bd scoop vanilla protein powder", "1\u00bd cup frozen berries", "2 stevia packets"],
    directions: ["\ud83e\uded9 BLEND: Puree cottage cheese with protein powder and stevia in a food processor.", "\ud83e\uded0 ADD: Fold in frozen berries and combine.", "\u2744\ufe0f SET: Serve immediately, or freeze 10\u201315 minutes for a thicker, cheesecake-like texture."],
    scienceNote: "Cottage cheese is one of the best sources of casein protein, which digests slowly \u2014 providing sustained amino acid release that supports overnight muscle repair for 40+ bodies.",
    proTip: "Use a mix of blueberries and raspberries for a tart, complex flavor profile.",
    pillar: "FEAST" as const,
  },
  {
    id: "B10",
    name: "PROTEIN PANCAKES",
    category: "BREAKFAST",
    calories: 320,
    time: "15 MIN",
    protein: 30,
    fat: 8,
    carbs: 28,
    ingredients: ["\u00bd cup oatmeal", "\u00bd cup cottage cheese", "3 egg whites (2/3 cup)", "2 packets of stevia", "Cinnamon to taste"],
    directions: ["\ud83e\udd63 BLEND: Mix all ingredients in bowl or puree in food processor for smoother texture.", "\ud83c\udf73 COOK: Cook on greased skillet at medium heat for about 2 minutes per side.", "\ud83e\udd5e SERVE: Flip when bubbles form and cook until firm. Top with Walden Farms Syrup."],
    scienceNote: "The oat and egg white combo in these pancakes creates a low-glycemic, high-protein breakfast that supports both muscle maintenance and stable blood sugar \u2014 two priorities after 40.",
    proTip: "For fluffier pancakes, let the batter rest 2 minutes before cooking.",
    pillar: "FEAST" as const,
  },
  {
    id: "B11",
    name: "THE ULTIMATE BREAKFAST SANDWICH",
    category: "BREAKFAST",
    calories: 310,
    time: "15 MIN",
    protein: 34,
    fat: 5,
    carbs: 32,
    ingredients: ["3 slices Ezekiel bread", "1 cup spinach", "1 small sliced tomato", "6 egg whites", "Balsamic vinegar", "Sriracha to taste"],
    directions: ["\ud83c\udf5e TOAST: Toast Ezekiel bread to desired level.", "\ud83e\udd6c SAUT\u00c9: Cook spinach in balsamic vinegar on low-medium heat until it shrinks.", "\ud83e\udd5a ASSEMBLE: Add egg whites on top of spinach, cook until firm. Stack with toast and tomato."],
    scienceNote: "Balsamic vinegar contains polyphenols that support cardiovascular health and blood pressure regulation \u2014 both critical health markers to manage after 40.",
    proTip: "Sriracha on this one is non-negotiable \u2014 it ties the whole sandwich together.",
    pillar: "FEAST" as const,
  },
  {
    id: "M01",
    name: "SEARED SCALLOPS WITH SPROUTS",
    category: "MAINS",
    calories: 310,
    time: "20 MIN",
    protein: 32,
    fat: 12,
    carbs: 14,
    ingredients: ["6 oz scallops", "2 tbsp olive oil (divided)", "2 tbsp rice wine vinegar", "1 cup diced brussels sprouts", "\u00bd cup sauerkraut (optional)"],
    directions: ["\ud83d\udd25 HEAT: Heat oil in skillet over medium-high until shimmering.", "\ud83e\udd66 VEGGIES: Add brussels sprouts, season with salt and pepper, stir continuously 5\u20136 min.", "\ud83c\udf4b FINISH: Stir in vinegar, scrape up brown bits, transfer to plate. Sear scallops 2 min per side."],
    scienceNote: "Scallops are rich in zinc and vitamin B12, both of which support testosterone production and cognitive function \u2014 two areas that benefit from nutritional support after 40.",
    proTip: "Pat scallops completely dry before searing \u2014 moisture is the enemy of a good crust.",
    pillar: "FEAST" as const,
  },
  {
    id: "M02",
    name: "STIR FRY CABBAGE AND PORK",
    category: "MAINS",
    calories: 340,
    time: "15 MIN",
    protein: 36,
    fat: 14,
    carbs: 12,
    ingredients: ["6 oz pork (cooked and shredded)", "2 tbsp Kerrygold butter", "\u00bd cup chopped celery", "2 cups shredded cabbage", "1/3 cup chopped onion", "4 tbsp Bragg's soy alternative"],
    directions: ["\ud83e\uddc8 HEAT: Heat butter in skillet until bubbly. Add celery and cook 1 minute.", "\ud83e\udd6c VEGGIES: Add cabbage and onion, stir-fry until tender-crisp, 2\u20133 minutes.", "\ud83e\udd69 FINISH: Add pork, pour in Bragg's, salt to taste. Stir well and cook 1 more minute."],
    scienceNote: "Cabbage is one of the most nutrient-dense, low-calorie vegetables available, providing glucosinolates that support liver detoxification \u2014 increasingly important as metabolic rate slows after 40.",
    proTip: "Use Kerrygold grass-fed butter specifically \u2014 the fat profile is measurably better for you.",
    pillar: "FEAST" as const,
  },
  {
    id: "M03",
    name: "LEAN STUFFED PEPPER",
    category: "MAINS",
    calories: 320,
    time: "35 MIN",
    protein: 38,
    fat: 10,
    carbs: 16,
    ingredients: ["6 oz cooked ground turkey", "2 tbsp coconut oil", "1 green pepper", "\u00bc cup chopped onion", "1/3 cup diced tomato", "Parsley, oregano, basil, rosemary, seasoned salt"],
    directions: ["\ud83e\udd58 COOK: Saut\u00e9 all veggies and spices in coconut oil 5\u201310 min until tender. Add turkey.", "\ud83e\uded1 STUFF: Seed pepper, cut in half, fill each half with the meat mixture.", "\ud83d\udd25 BAKE: Bake at 350\u00b0F for 25\u201330 minutes until pepper is tender."],
    scienceNote: "Bell peppers contain more vitamin C than oranges. Vitamin C is essential for collagen synthesis, supporting joint cartilage health \u2014 a critical concern for active 40+ adults.",
    proTip: "Use red or yellow peppers for a sweeter flavor and higher vitamin C content.",
    pillar: "FEAST" as const,
  },
  {
    id: "M04",
    name: "LEMON BUTTER ASPARAGUS",
    category: "MAINS",
    calories: 295,
    time: "15 MIN",
    protein: 34,
    fat: 14,
    carbs: 6,
    ingredients: ["~15 stalks of asparagus", "6 oz white fish (yellowtail suggested)", "1 tbsp lemon juice", "1 tbsp coconut oil", "1 tbsp Kerrygold butter"],
    directions: ["\ud83c\udf3f ASPARAGUS: Saut\u00e9 asparagus in coconut oil. When tender, drizzle lemon juice on top.", "\ud83e\uddc8 BUTTER: Move asparagus aside. Add butter to pan on medium-high heat.", "\ud83d\udc1f FISH: Add fish to butter, cook 2\u20133 min per side until crispy. Salt to taste and plate."],
    scienceNote: "Asparagus is one of the top food sources of folate, which supports cardiovascular health and DNA repair \u2014 both increasingly important biological processes after 40.",
    proTip: "The butter 'fries' the fish creating an incredible crispy exterior without breading.",
    pillar: "FEAST" as const,
  },
  {
    id: "M05",
    name: "HEALTHY HOLIDAY COMFORT",
    category: "MAINS",
    calories: 350,
    time: "25 MIN",
    protein: 40,
    fat: 10,
    carbs: 18,
    ingredients: ["6 oz baked turkey tenders", "2 cups chopped cauliflower", "2 tbsp Kerrygold butter", "\u00bd tbsp minced garlic", "\u00bd tsp Italian seasoning, salt & pepper", "1 green onion stalk (optional)"],
    directions: ["\ud83e\udd66 STEAM: Simmer cauliflower in water, covered, 12\u201315 minutes until very tender. Drain.", "\ud83e\uddc8 MASH: Add butter, garlic, spices to cauliflower. Mash until it resembles mashed potatoes.", "\ud83c\udf57 SERVE: Top with chives and pair with baked turkey tenders."],
    scienceNote: "Cauliflower mash delivers all the comfort of mashed potatoes with 70% fewer carbs, supporting better blood sugar control and reduced inflammation for 40+ metabolisms.",
    proTip: "For extra creaminess, add 2 tbsp of Greek yogurt when mashing.",
    pillar: "FEAST" as const,
  },
  {
    id: "M06",
    name: "LEMON ALMOND ROASTED SALAD",
    category: "MAINS",
    calories: 360,
    time: "30 MIN",
    protein: 42,
    fat: 14,
    carbs: 12,
    ingredients: ["6 oz skinless chicken breasts", "1/3 cup plain Greek yogurt", "1 tbsp olive oil", "12 pieces sliced almond", "1 tbsp lemon juice", "1 green onion diced, 1 tbsp fresh parsley"],
    directions: ["\ud83d\udd25 CHICKEN: Season chicken, bake at 400\u00b0F for 20\u201325 minutes until cooked through.", "\ud83c\udf30 TOAST: Toast almonds in dry nonstick skillet over medium-low, stirring until golden, 4\u20135 min.", "\ud83e\udd57 COMBINE: Mix chicken, almonds, lemon, green onion, parsley. Fold in yogurt until coated."],
    scienceNote: "Almonds provide magnesium, which supports over 300 enzymatic reactions in the body. Magnesium deficiency is extremely common after 40 and linked to muscle cramps and poor sleep.",
    proTip: "This works beautifully as a meal prep \u2014 make 3 days' worth and refrigerate.",
    pillar: "FEAST" as const,
  },
  {
    id: "M07",
    name: "LOW CARB BROCCOLI & TUNA SALAD",
    category: "MAINS",
    calories: 300,
    time: "10 MIN + CHILL",
    protein: 38,
    fat: 8,
    carbs: 16,
    ingredients: ["6 cups broccoli", "1\u00bd cans tuna", "Small onion, chopped", "1 cup plain Greek yogurt", "\u00bd cup chopped almonds", "2 tbsp red vinegar, lemon pepper"],
    directions: ["\ud83e\udd57 COMBINE: In large bowl: combine broccoli, tuna, onion, and almonds.", "\ud83e\uded9 DRESSING: In separate bowl: mix yogurt, vinegar, and seasonings.", "\u2744\ufe0f CHILL: Pour dressing over broccoli mix, stir well, refrigerate 1 hour before serving."],
    scienceNote: "Broccoli contains sulforaphane and DIM compounds that support healthy estrogen metabolism, important for both men and women managing hormonal changes after 40.",
    proTip: "Let it chill at least an hour \u2014 the flavors develop significantly.",
    pillar: "FEAST" as const,
  },
  {
    id: "M08",
    name: "SHRIMP & AVOCADO STUFFED SALAD",
    category: "MAINS",
    calories: 380,
    time: "10 MIN",
    protein: 30,
    fat: 22,
    carbs: 14,
    ingredients: ["3 large ripe avocados", "35 oz cooked shrimp (thawed, no tails)", "2 tbsp Greek yogurt", "2 tbsp fresh lime juice", "1 tbsp sriracha or hot sauce", "Salt and pepper to taste"],
    directions: ["\ud83e\udd51 PREP: Cut avocados in half, remove pit. Scoop flesh into a medium bowl.", "\ud83c\udf64 MIX: Add shrimp, yogurt, lime juice, sriracha, salt & pepper. Toss to combine.", "\ud83c\udf7d\ufe0f SERVE: Serve inside empty avocado skins for a stunning presentation."],
    scienceNote: "Avocado's monounsaturated fats paired with shrimp's lean protein creates a near-perfect anti-inflammatory meal, supporting joint health and cardiovascular function after 40.",
    proTip: "Serving in the avocado skin makes this visually impressive \u2014 great for guests.",
    pillar: "FEAST" as const,
  },
  {
    id: "M09",
    name: "HONEY MUSTARD CHICKEN SALAD",
    category: "MAINS",
    calories: 390,
    time: "15 MIN",
    protein: 44,
    fat: 16,
    carbs: 14,
    ingredients: ["6 oz boneless skinless chicken breast", "1 bag spinach", "2 ripe tomatoes", "1/3 cup red onion", "1/3 cup mustard", "8 tbsp olive oil, 4 stevia packets"],
    directions: ["\ud83c\udf6f DRESSING: Whisk mustard, olive oil & stevia together in small bowl until combined.", "\ud83e\udd57 BUILD: Build bowl with spinach, tomatoes, red onion.", "\ud83c\udf57 TOP: Top with heated chicken, drizzle dressing. Serve immediately."],
    scienceNote: "Mustard seeds contain isothiocyanates that have been shown to reduce inflammation markers. Combined with olive oil's oleocanthal, this dressing is essentially anti-inflammatory medicine.",
    proTip: "Serve the chicken warm on the cold salad \u2014 the temperature contrast elevates this dish.",
    pillar: "FEAST" as const,
  },
  {
    id: "M10",
    name: "GARLIC SHRIMP",
    category: "MAINS",
    calories: 340,
    time: "15 MIN",
    protein: 32,
    fat: 8,
    carbs: 32,
    ingredients: ["6 oz shrimp (tails removed)", "2 tbsp minced garlic", "1 cup cubed tomato", "Red wine vinegar, dried basil", "\u00bd tsp salt", "\u00bd cup white rice"],
    directions: ["\ud83e\uddc4 MARINATE: Combine salt, garlic, tomato, vinegar & basil. Toss shrimp to coat.", "\ud83c\udf73 COOK: Heat greased skillet to medium. Pour mixture on and cook until shrimp is pink.", "\ud83c\udf5a PLATE: Remove from heat and lay atop \u00bd cup of white rice."],
    scienceNote: "Garlic's allicin compound has been clinically shown to support healthy blood pressure and reduce LDL cholesterol \u2014 two of the most important cardiovascular markers to manage after 40.",
    proTip: "Fresh minced garlic from a bulb is significantly more potent than jarred \u2014 worth the extra 2 minutes.",
    pillar: "FEAST" as const,
  },
  {
    id: "M11",
    name: "TURKEY TACOS",
    category: "MAINS",
    calories: 360,
    time: "15 MIN",
    protein: 40,
    fat: 10,
    carbs: 24,
    ingredients: ["6 oz lean ground turkey", "3\u20134 large romaine lettuce leaves", "\u00bd cup pico de gallo", "\u00bd cup wild rice", "Garlic powder, cayenne, onion powder, chili powder"],
    directions: ["\ud83c\udf36\ufe0f COOK: Saut\u00e9 turkey with all spices on medium-high until fully cooked.", "\ud83c\udf45 ADD: Stir in pico de gallo and continue cooking until thoroughly mixed.", "\ud83e\udd6c ASSEMBLE: Add to rice, distribute into lettuce shells. Top with hot sauce."],
    scienceNote: "Using romaine lettuce as a taco shell eliminates empty carbs while adding vitamin K, which supports bone density \u2014 a key concern for both men and women after 40.",
    proTip: "Wild rice has significantly more protein and fiber than white rice \u2014 don't substitute.",
    pillar: "FEAST" as const,
  },
  {
    id: "M12",
    name: "CHICKEN VEGGIE STIR FRY",
    category: "MAINS",
    calories: 370,
    time: "20 MIN",
    protein: 42,
    fat: 8,
    carbs: 30,
    ingredients: ["6 oz cooked skinless chicken breast", "\u00bd cup cooked brown rice", "\u00bd cup snap peas", "\u00bd cup broccoli", "Bragg's Amino Acid Soy Sauce Alternative", "Garlic powder, onion powder, red pepper flakes"],
    directions: ["\ud83d\udd2a PREP: Chop veggies into smaller pieces.", "\ud83e\udd62 SAUT\u00c9: Cook veggies in Bragg's AA with spices at medium heat, 3\u20134 minutes.", "\ud83c\udf57 COMBINE: Add shredded chicken and rice. Mix until fully coated in sauce."],
    scienceNote: "Snap peas are high in vitamin C and K while broccoli provides sulforaphane. This combo supports both immune function and the anti-inflammatory pathways that become more important after 40.",
    proTip: "Tear chicken into irregular pieces rather than cutting \u2014 creates better sauce adhesion.",
    pillar: "FEAST" as const,
  },
  {
    id: "M13",
    name: "GUILT FREE PULLED PORK",
    category: "MAINS",
    calories: 380,
    time: "20 MIN",
    protein: 38,
    fat: 10,
    carbs: 34,
    ingredients: ["6 oz shredded pork", "\u00bc cup balsamic vinegar", "1 tbsp Worcestershire sauce", "1 tbsp minced garlic, 2 stevia packets", "Red pepper flakes to taste", "2/3 cup mashed sweet potato"],
    directions: ["\ud83e\udd58 SIMMER: Combine all ingredients (minus potato) in greased skillet on medium-low.", "\u23f1\ufe0f COOK: Cover and let simmer 5\u20136 minutes until flavors meld.", "\ud83c\udf60 SERVE: Remove from heat, pair with baked sweet potato. Top potato with cinnamon/stevia."],
    scienceNote: "Sweet potato's beta-carotene converts to vitamin A, supporting immune function and skin elasticity. Combined with pork's zinc content, this meal supports multiple 40+ health priorities.",
    proTip: "The balsamic + stevia combo creates a BBQ-like sweet-tangy sauce without the sugar load.",
    pillar: "FEAST" as const,
  },
  {
    id: "M14",
    name: "SWEET SUMMER SALAD",
    category: "MAINS",
    calories: 310,
    time: "10 MIN",
    protein: 36,
    fat: 8,
    carbs: 20,
    ingredients: ["6 oz cooked skinless chicken breast", "2 cups spinach", "2/3 cup mixed berries", "Handful of cherry tomatoes", "Apple Cider Vinaigrette for dressing"],
    directions: ["\ud83e\udd57 BUILD: In a large bowl, toss spinach, tomatoes, and berries.", "\ud83c\udf57 TOP: Top with sliced or diced chicken.", "\ud83e\uded9 DRESS: Drizzle with Apple Cider Vinaigrette before serving."],
    scienceNote: "Apple cider vinegar has been clinically shown to improve insulin sensitivity, supporting blood sugar regulation after meals \u2014 particularly beneficial for 40+ adults managing metabolic health.",
    proTip: "The berries make this feel indulgent \u2014 nobody believes it's a 'diet' meal.",
    pillar: "FEAST" as const,
  },
  {
    id: "M15",
    name: "LOADED BAKED POTATO",
    category: "MAINS",
    calories: 320,
    time: "10 MIN",
    protein: 32,
    fat: 4,
    carbs: 38,
    ingredients: ["1 small baked potato (~2/3 cup)", "6 oz nonfat cottage cheese", "\u00bd cup pico de gallo", "\u00bc cup chopped green onion"],
    directions: ["\ud83e\udd54 BAKE: Poke holes in potato with fork and microwave until cooked through.", "\ud83e\uddc0 TOP: Layer cottage cheese on top, place under broiler 1 minute if you prefer it warm.", "\ud83c\udf3f FINISH: Top with pico de gallo and green onion. Serve immediately."],
    scienceNote: "Potatoes contain resistant starch when cooled slightly, which acts as a prebiotic feeding beneficial gut bacteria and improving colon health \u2014 increasingly important after 40.",
    proTip: "Cottage cheese as a sour cream replacement is a cheat code \u2014 same creamy texture, triple the protein.",
    pillar: "FEAST" as const,
  },
  {
    id: "M16",
    name: "GRILLED TUNA BURGER & SALAD",
    category: "MAINS",
    calories: 330,
    time: "15 MIN",
    protein: 40,
    fat: 8,
    carbs: 22,
    ingredients: ["1\u00bd cans tuna", "1 egg white", "\u00bd cup dry oats", "\u00bc tsp oregano, onion & garlic powder", "2 cups romaine lettuce", "\u00bd cup mixed veggies of choice"],
    directions: ["\ud83e\uded9 MIX: Combine tuna, egg white, oats & spices. Form into a burger patty.", "\ud83c\udf73 COOK: Cook on greased pan at medium heat, 3 minutes per side until finished.", "\ud83e\udd57 SERVE: Serve with side salad of lettuce and veggies, choice of dressing."],
    scienceNote: "Canned tuna is one of the most cost-effective sources of omega-3 fatty acids, which reduce systemic inflammation and support brain health \u2014 both critical priorities after 40.",
    proTip: "Refrigerate the patty 15 minutes before cooking \u2014 it holds together much better.",
    pillar: "FEAST" as const,
  },
  {
    id: "M17",
    name: "CHICKEN TACOS",
    category: "MAINS",
    calories: 350,
    time: "15 MIN",
    protein: 44,
    fat: 8,
    carbs: 22,
    ingredients: ["6 oz cooked skinless chicken breast", "\u00bd cup black refried beans", "\u00bc cup chopped green onion", "\u00bd cup pico de gallo", "4 pieces romaine lettuce", "\u00bc tsp red pepper flakes"],
    directions: ["\ud83e\uded8 BEANS: Heat beans in saucepan on medium-low. Mix in green onion, pico & red pepper flakes.", "\ud83e\udd6c SHELLS: Distribute bean mixture into lettuce shells.", "\ud83c\udf57 TOP: Slice chicken into thin strips, place in shells. Add salt or sauce to taste."],
    scienceNote: "Black beans are one of the best dietary sources of plant-based iron and folate, nutrients that support cardiovascular health and cognitive function \u2014 both key 40+ priorities.",
    proTip: "Black beans dramatically increase the fiber content, making this one of the most satisfying meals in the book.",
    pillar: "FEAST" as const,
  },
  {
    id: "M18",
    name: "HEALTHY FRIED RICE",
    category: "MAINS",
    calories: 355,
    time: "15 MIN",
    protein: 36,
    fat: 8,
    carbs: 36,
    ingredients: ["\u00bd cup cooked brown rice", "3 oz cooked chicken", "3 egg whites", "1 cup mixed veggies", "Onion & chili powder", "Bragg's Soy Sauce Alternative"],
    directions: ["\ud83e\udd5a EGGS: Spray skillet with PAM, medium heat. Add eggs and scramble.", "\ud83c\udf5a RICE: Add rice and mixed veggies to the scrambled eggs. Continue mixing.", "\ud83c\udf57 FINISH: Add shredded chicken and spices. Saut\u00e9 in Bragg's, remove and serve."],
    scienceNote: "Brown rice contains significantly more magnesium, phosphorus, and B vitamins than white rice, supporting the nervous system and energy metabolism that tends to slow after 40.",
    proTip: "Day-old rice works best for fried rice \u2014 fresh rice is too moist and gets gummy.",
    pillar: "FEAST" as const,
  },
  {
    id: "M19",
    name: "QUINOA CHICKEN SALAD",
    category: "MAINS",
    calories: 410,
    time: "30 MIN",
    protein: 48,
    fat: 10,
    carbs: 32,
    ingredients: ["6 oz cooked skinless chicken breasts", "\u00bd cup cooked quinoa", "\u00bd cup garbanzo beans", "1\u00bd cup fresh kale", "\u00bc cup chopped red onion", "Lemon zest, white wine vinegar, cumin"],
    directions: ["\ud83e\udd57 COMBINE: Toss chicken, quinoa, garbanzo beans, kale, and red onion in large bowl.", "\ud83c\udf4b DRESS: Mix lemon juice/zest, white wine vinegar, cumin, salt & pepper. Pour over salad.", "\ud83e\udd62 TOSS: Toss until everything is evenly coated. Serve chilled or at room temperature."],
    scienceNote: "Quinoa is one of the only plant foods containing all 9 essential amino acids, making it ideal for maintaining muscle protein synthesis in the 40+ body where protein efficiency naturally decreases.",
    proTip: "Massage the kale with a bit of lemon juice first \u2014 it breaks down the tough fibers.",
    pillar: "FEAST" as const,
  },
  {
    id: "M20",
    name: "SEARED WHITEFISH COUSCOUS SALAD",
    category: "MAINS",
    calories: 360,
    time: "20 MIN",
    protein: 38,
    fat: 8,
    carbs: 34,
    ingredients: ["6 oz white fish", "1 cup couscous", "1 cup chopped cucumber", "\u00bd cup diced red onion", "2 tbsp fresh lemon juice", "2 tbsp fresh mint leaves, garlic"],
    directions: ["\ud83d\udc1f SEASON: Add salt and pepper to both sides of white fish.", "\ud83c\udf3f COUSCOUS: Reheat couscous, stir in onion, mint, lemon juice and cucumber.", "\ud83c\udf4b PLATE: Serve fish on the side with fresh squeezed lemon."],
    scienceNote: "White fish is exceptionally high in selenium, a mineral that supports thyroid function \u2014 a key metabolic regulator that becomes increasingly important to support after 40.",
    proTip: "Fresh mint is non-negotiable in this recipe \u2014 it transforms the whole dish.",
    pillar: "FEAST" as const,
  },
  {
    id: "M21",
    name: "THAI BEEF SALAD",
    category: "MAINS",
    calories: 380,
    time: "20 MIN",
    protein: 40,
    fat: 16,
    carbs: 14,
    ingredients: ["6 oz lean steak", "100g baby cos lettuce hearts", "\u00bd cup mint, coriander, bean sprouts, tomato", "\u00bd cucumber sliced, \u00bd red onion sliced", "1 tbsp lime juice, 1 tsp Bragg's soy alternative", "1 tsp chili flakes"],
    directions: ["\ud83e\udd69 MARINATE: Marinate steak in soy sauce, fish sauce & lime juice.", "\ud83d\udd25 COOK: Cook steak 2\u20133 min per side to desired texture. Set aside to rest.", "\ud83e\udd57 ASSEMBLE: Combine all veggies in bowl. Thinly slice steak across grain and add on top."],
    scienceNote: "Lean red meat provides the highest bioavailable source of iron and zinc. After 40, absorption of these minerals decreases, making high-quality red meat a valuable part of a strategic diet.",
    proTip: "Slice steak against the grain \u2014 it makes a dramatic difference in tenderness.",
    pillar: "FEAST" as const,
  },
  {
    id: "M22",
    name: "AVOCADO TUNA SALAD",
    category: "MAINS",
    calories: 340,
    time: "5 MIN",
    protein: 36,
    fat: 16,
    carbs: 12,
    ingredients: ["\u00bd avocado", "1\u00bd cans tuna", "1 cup diced tomato", "1\u00bd tbsp lime juice", "\u00bd tsp chili powder", "Sriracha to taste"],
    directions: ["\ud83e\udd51 MASH: Mash avocado in a bowl.", "\ud83d\udc1f COMBINE: Add tuna and diced tomato to mashed avocado.", "\ud83c\udf36\ufe0f SEASON: Stir in lime juice and chili powder. Top with sriracha."],
    scienceNote: "The combination of omega-3s from tuna and monounsaturated fats from avocado creates a synergistic anti-inflammatory effect that supports brain health and joint function after 40.",
    proTip: "This is a 5-minute power meal \u2014 keep canned tuna and avocados stocked at all times.",
    pillar: "FEAST" as const,
  },
  {
    id: "M23",
    name: "SPICY THAI SHRIMP SALAD",
    category: "MAINS",
    calories: 295,
    time: "15 MIN",
    protein: 30,
    fat: 14,
    carbs: 10,
    ingredients: ["6 oz jumbo shrimp (no tail)", "1 tbsp lime juice", "1 tsp fish sauce", "2 tbsp coconut oil, 2 stevia packets", "\u00bd tsp crushed red pepper", "2 handfuls mixed greens + 1 veggie of choice"],
    directions: ["\ud83e\uded9 DRESSING: Whisk lime juice, fish sauce, coconut oil, stevia & red pepper in large bowl.", "\ud83c\udf64 ADD: Add shrimp, greens and veggies to dressing bowl.", "\ud83e\udd57 TOSS: Add fresh herbs if desired. Toss everything to coat and serve."],
    scienceNote: "Shrimp is one of the leanest protein sources available, providing iodine that directly supports thyroid function and the metabolic regulation that becomes critical after 40.",
    proTip: "Fish sauce is the secret weapon \u2014 just a teaspoon adds incredible depth.",
    pillar: "FEAST" as const,
  },
  {
    id: "M24",
    name: "CRISPY CHICKEN & BRUSSEL",
    category: "MAINS",
    calories: 340,
    time: "20 MIN",
    protein: 40,
    fat: 16,
    carbs: 8,
    ingredients: ["6 oz skinless chicken breast", "1 cup brussels sprouts (halved)", "2 tbsp coconut oil", "\u00bc tsp garlic powder", "1 tbsp lemon juice"],
    directions: ["\ud83c\udf3f SPROUTS: Toss brussels in 1 tbsp coconut oil, garlic powder and salt.", "\ud83c\udf73 CHICKEN: Heat skillet to medium-high. Add remaining oil, fry thinly sliced chicken until crispy.", "\ud83c\udf4b COMBINE: Add sprouts to skillet with chicken. Saut\u00e9 on medium-low, add lemon juice."],
    scienceNote: "Brussels sprouts contain more vitamin C per serving than oranges, supporting collagen synthesis. Paired with lean protein, this meal is specifically designed for tissue repair and recovery after 40.",
    proTip: "The key is getting the chicken truly crispy before adding the sprouts \u2014 patience pays off.",
    pillar: "FEAST" as const,
  },
  {
    id: "M25",
    name: "THAI PEANUT CHICKEN",
    category: "MAINS",
    calories: 395,
    time: "20 MIN",
    protein: 42,
    fat: 22,
    carbs: 12,
    ingredients: ["6 oz skinless chicken breast", "2 tbsp peanut butter", "2 tbsp Bragg's soy sauce alternative", "1 tbsp lemon juice", "1 tbsp rice vinegar", "1 cup mixed veggies of choice"],
    directions: ["\ud83e\udd5c SAUCE: Microwave peanut butter slightly. Whisk with Bragg's, lemon, vinegar & cayenne.", "\ud83c\udf57 CHICKEN: Shred or slice cooked chicken into thin pieces.", "\ud83e\udd57 SERVE: Toss chicken and veggies in sauce. Top with salt, green onion or sesame."],
    scienceNote: "Peanut butter's monounsaturated fats support joint lubrication. The lean protein from chicken helps maintain muscle mass as metabolism slows with age after 40.",
    proTip: "Add sriracha or chili oil for extra heat. Great over cauliflower rice for low-carb.",
    pillar: "FEAST" as const,
  },
  {
    id: "S01",
    name: "BLUEBERRY PIE SMOOTHIE",
    category: "SHAKES",
    calories: 220,
    time: "5 MIN",
    protein: 26,
    fat: 2,
    carbs: 24,
    ingredients: ["1 scoop vanilla protein powder", "2 handfuls spinach", "2/3 cup mixed frozen berries", "1 cup cold water", "1 tsp vanilla, 2 stevia packets", "Dash of cinnamon"],
    directions: ["\ud83e\uded0 BLEND: Add all ingredients to blender.", "\u26a1 MIX: Blend until smooth and creamy.", "\ud83e\udd64 SERVE: Pour into glass and serve immediately."],
    scienceNote: "Blueberries are among the highest antioxidant foods available, providing anthocyanins that cross the blood-brain barrier and directly support cognitive function \u2014 a key 40+ priority.",
    proTip: "The spinach is completely undetectable in flavor \u2014 don't skip it. Free vegetables.",
    pillar: "FEAST" as const,
  },
  {
    id: "S02",
    name: "VANILLA ALMOND SHAKE",
    category: "SHAKES",
    calories: 310,
    time: "5 MIN",
    protein: 36,
    fat: 12,
    carbs: 14,
    ingredients: ["1\u00bd scoops vanilla protein powder", "2 tbsp smooth peanut butter", "1 cup water", "Handful of ice"],
    directions: ["\ud83e\udd5c ADD: Combine protein powder, peanut butter, water and ice in blender.", "\u26a1 BLEND: Blend until smooth. Add more ice for a thicker consistency.", "\ud83e\udd64 SERVE: Pour and serve immediately for best texture."],
    scienceNote: "The combination of fast-digesting whey protein and slow-digesting fat from peanut butter creates an extended release of amino acids \u2014 supporting muscle repair over 4\u20136 hours post-workout.",
    proTip: "This doubles as a post-workout recovery shake and a meal replacement.",
    pillar: "FEAST" as const,
  },
  {
    id: "S03",
    name: "CAKE FOR BREAKFAST",
    category: "SHAKES",
    calories: 260,
    time: "5 MIN",
    protein: 28,
    fat: 4,
    carbs: 28,
    ingredients: ["1 scoop vanilla protein powder", "2/3 cup ground dry oats", "1 tsp vanilla, 1 stevia packet", "Dash of salt & sprinkles", "1 cup water, handful of ice"],
    directions: ["\ud83c\udf82 ADD: Combine all ingredients in blender.", "\u26a1 BLEND: Blend until smooth and thick.", "\ud83e\udd64 SERVE: Pour into glass. Add sprinkles on top for the full experience."],
    scienceNote: "Starting the day with protein-enriched oats stabilizes blood glucose for 3\u20134 hours, reducing the mid-morning cortisol spike that contributes to belly fat accumulation after 40.",
    proTip: "Grind the oats in a coffee grinder first for an ultra-smooth, true milkshake texture.",
    pillar: "FEAST" as const,
  },
  {
    id: "S04",
    name: "PB SANDWICH SHAKE",
    category: "SHAKES",
    calories: 310,
    time: "5 MIN",
    protein: 36,
    fat: 12,
    carbs: 14,
    ingredients: ["1\u00bd scoops strawberry or chocolate protein", "2 tbsp smooth peanut butter", "1 cup water", "Handful of ice"],
    directions: ["\ud83e\udd5c COMBINE: Add protein, peanut butter, water and ice to blender.", "\u26a1 BLEND: Blend 30\u201345 seconds until smooth and frothy.", "\ud83e\udd64 SERVE: Pour and enjoy. This genuinely tastes like a dessert."],
    scienceNote: "Peanut butter is one of the most calorically efficient fat sources for supporting testosterone production \u2014 a key hormone that declines after 40 and directly impacts energy and muscle retention.",
    proTip: "Use strawberry protein for the classic PB&J experience. Chocolate for something richer.",
    pillar: "FEAST" as const,
  },
  {
    id: "D01",
    name: "BALSAMIC VINEGAR DRESSING",
    category: "DRESSINGS",
    calories: 20,
    time: "2 MIN",
    protein: 0,
    fat: 0,
    carbs: 5,
    ingredients: ["\u00bd cup water", "\u00bc cup balsamic vinegar", "2 packets splenda/stevia", "1 tsp onion salt", "1 tsp garlic powder", "\u00bc tsp dried mustard"],
    directions: ["\ud83e\uded9 COMBINE: Add all ingredients to a jar or container with a tight lid.", "\ud83e\udd1d SHAKE: Shake vigorously until thoroughly combined.", "\u2744\ufe0f STORE: Refrigerate and shake again before each use."],
    scienceNote: "Balsamic vinegar contains acetic acid and polyphenols that help regulate blood sugar response after meals \u2014 making this the smart dressing choice for 40+ adults managing metabolic health.",
    proTip: "Variations: add dill seed for Dilly Dressing, or minced green onions for Green Onion Dressing.",
    pillar: "FEAST" as const,
  },
  {
    id: "D02",
    name: "VERSATILE VINEGAR DRESSING",
    category: "DRESSINGS",
    calories: 10,
    time: "2 MIN",
    protein: 0,
    fat: 0,
    carbs: 2,
    ingredients: ["\u00bd cup cold water", "\u00bd cup white vinegar", "\u00bd tsp salt", "\u00bd tsp dry mustard", "1/8 tsp pepper", "1 dash paprika"],
    directions: ["\ud83e\uded9 COMBINE: Add all ingredients to a small jar.", "\ud83e\udd1d SHAKE: Shake until fully combined.", "\ud83e\udd57 USE: Pour over salads. Refrigerate remaining dressing."],
    scienceNote: "White vinegar's acetic acid has been shown in multiple studies to reduce post-meal blood glucose spikes by up to 20%, supporting insulin sensitivity that tends to decline after 40.",
    proTip: "The lightest dressing in the book \u2014 perfect for days when you're watching total calories.",
    pillar: "FEAST" as const,
  },
  {
    id: "D03",
    name: "'HONEY' MUSTARD DRESSING",
    category: "DRESSINGS",
    calories: 35,
    time: "2 MIN",
    protein: 1,
    fat: 1,
    carbs: 7,
    ingredients: ["1 cup balsamic vinegar", "\u00bc cup yellow or spicy mustard", "3 packets of stevia"],
    directions: ["\ud83c\udf6f MIX: Combine balsamic vinegar, mustard and stevia in a bowl.", "\ud83e\udd44 WHISK: Whisk until smooth and stevia is fully dissolved.", "\ud83e\udd57 TOSS: Toss directly into salad and serve."],
    scienceNote: "Mustard contains selenium and omega-3 fatty acids, while balsamic provides resveratrol. Together they create a dressing with genuine cardiovascular benefits for 40+ adults.",
    proTip: "This pairs perfectly with the Honey Mustard Chicken Salad \u2014 make extra and keep refrigerated.",
    pillar: "FEAST" as const,
  },
] as const;

export type TUTKRecipe = (typeof TUTK_RECIPES)[0];
