/**
 * PANTHER BRAIN CATALOGUE — Clinical Exercise Database
 * © 2026 Turned Up Fitness LLC. All rights reserved.
 *
 * Full clinical schema with NASM phases, UCS/LCS risk flags,
 * sarcopenia weighting, 40+ suitability scores, and corrective protocols.
 */

export type Difficulty = "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "ATHLETE";
export type Category = "ALL" | "STRENGTH" | "MOBILITY" | "CORRECTIVE" | "CONDITIONING" | "RECOVERY";

export interface ClinicalFlags {
  upperCrossedRisk: boolean;
  lowerCrossedRisk: boolean;
  activationCues: string[];
  compensationsToWatch: string[];
  inhibitTargets: string[];
  activateTargets: string[];
}

export interface CatalogueExercise {
  id: string;
  name: string;
  category: Category;
  subcategory: string;
  movementPattern: string;
  difficulty: Difficulty;
  corrective: boolean;
  over40Suitability: number;   // 0-1
  sarcopeniaWeight: number;    // 0-1
  nasmPhase: string[];         // ["1","2","3","4","5"]
  clinicalFlags: ClinicalFlags;
  equipment: string[];
  tags: string[];
}

export const NASM_PHASE_LABEL: Record<string, string> = {
  "1": "PHASE 1: STABILIZATION",
  "2": "PHASE 2: STRENGTH ENDURANCE",
  "3": "PHASE 3: HYPERTROPHY",
  "4": "PHASE 4: MAXIMAL STRENGTH",
  "5": "PHASE 5: POWER",
};

export const DIFFICULTY_COLOR: Record<Difficulty, string> = {
  BEGINNER:     "#00ff88",
  INTERMEDIATE: "#00aaff",
  ADVANCED:     "#ff9933",
  ATHLETE:      "#ff6b35",
};

export const DIFFICULTY_LABEL: Record<Difficulty, string> = {
  BEGINNER:     "● BEGINNER",
  INTERMEDIATE: "● INTERMEDIATE",
  ADVANCED:     "● ADVANCED",
  ATHLETE:      "● ATHLETE",
};

export const CATEGORIES: Category[] = [
  "ALL", "STRENGTH", "MOBILITY", "CORRECTIVE", "CONDITIONING", "RECOVERY",
];

export const CATEGORY_ICONS: Record<Category, string> = {
  ALL:          "⬡",
  STRENGTH:     "💪",
  MOBILITY:     "🌀",
  CORRECTIVE:   "✏️",
  CONDITIONING: "⚡",
  RECOVERY:     "🔄",
};

export const PANTHER_BRAIN: { exercises: CatalogueExercise[] } = {
  exercises: [
    // ── STRENGTH ──────────────────────────────────────────────────────────────
    {
      id: "STR-001",
      name: "Barbell Back Squat",
      category: "STRENGTH",
      subcategory: "Lower Body",
      movementPattern: "Squat",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.72,
      sarcopeniaWeight: 0.92,
      nasmPhase: ["3","4"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Drive knees out", "Chest tall", "Brace core before descent"],
        compensationsToWatch: ["Knees caving in", "Forward lean", "Heel rise"],
        inhibitTargets: ["Hip flexors", "TFL", "Adductors"],
        activateTargets: ["Glutes", "VMO", "Core"],
      },
      equipment: ["barbell", "squat_rack"],
      tags: ["compound", "strength", "lower_body", "posterior_chain"],
    },
    {
      id: "STR-002",
      name: "Conventional Deadlift",
      category: "STRENGTH",
      subcategory: "Posterior Chain",
      movementPattern: "Hinge",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.68,
      sarcopeniaWeight: 0.95,
      nasmPhase: ["3","4","5"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Pull the floor apart", "Lat engagement before lift", "Lock hips at top"],
        compensationsToWatch: ["Back rounding", "Bar drift", "Knee cave"],
        inhibitTargets: ["Erectors (if overactive)", "Hip flexors"],
        activateTargets: ["Glutes", "Hamstrings", "Lats"],
      },
      equipment: ["barbell"],
      tags: ["compound", "strength", "king_lift", "posterior_chain"],
    },
    {
      id: "STR-003",
      name: "Goblet Squat",
      category: "STRENGTH",
      subcategory: "Lower Body",
      movementPattern: "Squat",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.91,
      sarcopeniaWeight: 0.85,
      nasmPhase: ["1","2","3"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: false,
        activationCues: ["Elbows inside knees", "Sit tall", "Drive up through heels"],
        compensationsToWatch: ["Forward lean", "Heel rise"],
        inhibitTargets: ["Hip flexors", "Calves"],
        activateTargets: ["Glutes", "Core", "Upper back"],
      },
      equipment: ["dumbbell", "kettlebell"],
      tags: ["beginner_loaded", "form_builder", "corrective"],
    },
    {
      id: "STR-004",
      name: "Dumbbell Romanian Deadlift",
      category: "STRENGTH",
      subcategory: "Posterior Chain",
      movementPattern: "Hinge",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.88,
      sarcopeniaWeight: 0.87,
      nasmPhase: ["1","2","3"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Push hips back", "Soft knee", "Bar stays close to legs"],
        compensationsToWatch: ["Back rounding", "Knees locking out"],
        inhibitTargets: ["Hip flexors", "Lumbar erectors"],
        activateTargets: ["Hamstrings", "Glutes", "Core"],
      },
      equipment: ["dumbbell"],
      tags: ["hamstring_dominant", "hip_hinge", "corrective"],
    },
    {
      id: "STR-005",
      name: "Overhead Press",
      category: "STRENGTH",
      subcategory: "Upper Body Push",
      movementPattern: "Push",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.75,
      sarcopeniaWeight: 0.80,
      nasmPhase: ["2","3","4"],
      clinicalFlags: {
        upperCrossedRisk: true,
        lowerCrossedRisk: false,
        activationCues: ["Press through the ceiling", "Ribs down", "Glutes tight"],
        compensationsToWatch: ["Lower back arch", "Forward head", "Elbow flare"],
        inhibitTargets: ["Upper traps", "Pec minor", "Levator scapulae"],
        activateTargets: ["Lower traps", "Serratus anterior", "Rotator cuff"],
      },
      equipment: ["barbell", "dumbbell"],
      tags: ["shoulder", "overhead", "compound"],
    },
    {
      id: "STR-006",
      name: "Pull-Up",
      category: "STRENGTH",
      subcategory: "Upper Body Pull",
      movementPattern: "Pull",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.70,
      sarcopeniaWeight: 0.88,
      nasmPhase: ["2","3","4"],
      clinicalFlags: {
        upperCrossedRisk: true,
        lowerCrossedRisk: false,
        activationCues: ["Pull elbows to hips", "Chest to bar", "Dead hang start"],
        compensationsToWatch: ["Shrugging shoulders", "Kipping without control"],
        inhibitTargets: ["Upper traps", "Biceps (if dominant)"],
        activateTargets: ["Lats", "Lower traps", "Rhomboids"],
      },
      equipment: ["pull_up_bar"],
      tags: ["bodyweight", "compound", "back", "calisthenics"],
    },
    {
      id: "STR-007",
      name: "Bulgarian Split Squat",
      category: "STRENGTH",
      subcategory: "Unilateral Lower",
      movementPattern: "Lunge",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.78,
      sarcopeniaWeight: 0.90,
      nasmPhase: ["2","3"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Back knee down controlled", "Front heel stays", "Torso upright"],
        compensationsToWatch: ["Front knee cave", "Forward lean", "Hip shift"],
        inhibitTargets: ["Hip flexors", "TFL"],
        activateTargets: ["Glutes", "VMO", "Core"],
      },
      equipment: ["bodyweight", "dumbbell"],
      tags: ["unilateral", "glute_dominant", "quad"],
    },
    {
      id: "STR-008",
      name: "Kettlebell Swing",
      category: "STRENGTH",
      subcategory: "Explosive Power",
      movementPattern: "Hinge",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.80,
      sarcopeniaWeight: 0.88,
      nasmPhase: ["2","3","5"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Hips snap — not arms", "Glute squeeze at top", "Lat engagement on descent"],
        compensationsToWatch: ["Squatting the swing", "Hyperextending lumbar at top"],
        inhibitTargets: ["Hip flexors", "Lumbar erectors"],
        activateTargets: ["Glutes", "Hamstrings", "Core"],
      },
      equipment: ["kettlebell"],
      tags: ["explosive", "conditioning", "hip_power", "ballistic"],
    },

    // ── CORRECTIVE ────────────────────────────────────────────────────────────
    {
      id: "COR-001",
      name: "Wall Angel",
      category: "CORRECTIVE",
      subcategory: "Upper Crossed Syndrome",
      movementPattern: "Mobility",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.97,
      sarcopeniaWeight: 0.60,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: true,
        lowerCrossedRisk: false,
        activationCues: ["Keep low back flat to wall", "Slide arms without losing contact", "Chin tucked"],
        compensationsToWatch: ["Low back arching off wall", "Shoulders shrugging", "Head jutting forward"],
        inhibitTargets: ["Upper traps", "Pec minor", "Levator scapulae"],
        activateTargets: ["Lower traps", "Deep neck flexors", "Serratus anterior"],
      },
      equipment: ["bodyweight"],
      tags: ["UCS", "corrective", "posture", "shoulder_health"],
    },
    {
      id: "COR-002",
      name: "Hip 90/90 Stretch",
      category: "CORRECTIVE",
      subcategory: "Lower Crossed Syndrome",
      movementPattern: "Mobility",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.96,
      sarcopeniaWeight: 0.55,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Sit tall, not hunched", "Both sit bones down", "Breathe into the hip"],
        compensationsToWatch: ["Leaning away from stretch", "Rounding lumbar"],
        inhibitTargets: ["Hip flexors", "Piriformis", "TFL"],
        activateTargets: ["Glute med", "Hip external rotators"],
      },
      equipment: ["bodyweight"],
      tags: ["LCS", "corrective", "hip_mobility", "flexibility"],
    },
    {
      id: "COR-003",
      name: "Glute Bridge",
      category: "CORRECTIVE",
      subcategory: "Glute Activation",
      movementPattern: "Hinge",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.98,
      sarcopeniaWeight: 0.75,
      nasmPhase: ["1","2"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Drive hips like a striking panther", "Squeeze glutes at top", "Neutral spine"],
        compensationsToWatch: ["Hamstring cramping (hip flexor dominance)", "Lumbar hyperextension"],
        inhibitTargets: ["Hip flexors", "Lumbar erectors"],
        activateTargets: ["Glutes", "Hamstrings", "Core"],
      },
      equipment: ["bodyweight"],
      tags: ["posterior_chain", "rehab", "activation", "corrective"],
    },
    {
      id: "COR-004",
      name: "Thoracic Rotation",
      category: "CORRECTIVE",
      subcategory: "Spinal Mobility",
      movementPattern: "Rotation",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.99,
      sarcopeniaWeight: 0.50,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: true,
        lowerCrossedRisk: true,
        activationCues: ["Rotate from mid-back, not lumbar", "Keep hips square", "Exhale into rotation"],
        compensationsToWatch: ["Lumbar rotation substituting for thoracic", "Hip shifting"],
        inhibitTargets: ["Thoracic extensors (if stiff)", "Lumbar rotators"],
        activateTargets: ["Thoracic rotators", "Obliques"],
      },
      equipment: ["bodyweight"],
      tags: ["spinal_health", "corrective", "rotation", "mobility"],
    },
    {
      id: "COR-005",
      name: "Dead Bug",
      category: "CORRECTIVE",
      subcategory: "Core Stability",
      movementPattern: "Stability",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.97,
      sarcopeniaWeight: 0.70,
      nasmPhase: ["1","2"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Low back flat to floor throughout", "Exhale on extension", "Slow and controlled"],
        compensationsToWatch: ["Low back arching", "Breath holding", "Hip flexor dominance"],
        inhibitTargets: ["Hip flexors", "Lumbar erectors"],
        activateTargets: ["Transverse abdominis", "Multifidus", "Diaphragm"],
      },
      equipment: ["bodyweight"],
      tags: ["core_stability", "corrective", "anti_extension", "rehab"],
    },

    // ── MOBILITY ──────────────────────────────────────────────────────────────
    {
      id: "MOB-001",
      name: "World's Greatest Stretch",
      category: "MOBILITY",
      subcategory: "Full Body",
      movementPattern: "Locomotion",
      difficulty: "BEGINNER",
      corrective: false,
      over40Suitability: 0.94,
      sarcopeniaWeight: 0.65,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: false,
        activationCues: ["Step long", "Elbow to floor", "Rotate fully, eyes follow hand"],
        compensationsToWatch: ["Knee cave on front leg", "Lumbar flexion"],
        inhibitTargets: ["Hip flexors", "Thoracic extensors"],
        activateTargets: ["Hip external rotators", "Thoracic rotators"],
      },
      equipment: ["bodyweight"],
      tags: ["full_body", "warm_up", "mobility", "flexibility"],
    },
    {
      id: "MOB-002",
      name: "Ankle Circles + Dorsiflexion",
      category: "MOBILITY",
      subcategory: "Ankle",
      movementPattern: "Stability",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.99,
      sarcopeniaWeight: 0.45,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Full range circles", "Drive knee over 5th toe on dorsiflexion", "Keep heel down"],
        compensationsToWatch: ["Heel rising", "Pronation collapsing"],
        inhibitTargets: ["Gastrocnemius", "Soleus", "Peroneals"],
        activateTargets: ["Tibialis anterior", "Intrinsic foot muscles"],
      },
      equipment: ["bodyweight"],
      tags: ["ankle_mobility", "corrective", "foundation", "injury_prevention"],
    },
    {
      id: "MOB-003",
      name: "Cat-Cow",
      category: "MOBILITY",
      subcategory: "Spinal",
      movementPattern: "Stability",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.99,
      sarcopeniaWeight: 0.50,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: true,
        lowerCrossedRisk: true,
        activationCues: ["Breathe into each position", "Full spinal wave", "No rushing"],
        compensationsToWatch: ["Only moving lumbar", "Neck hyperextension"],
        inhibitTargets: ["Thoracic extensors", "Hip flexors"],
        activateTargets: ["Spinal erectors", "Multifidus", "Abdominals"],
      },
      equipment: ["bodyweight"],
      tags: ["spinal_health", "warm_up", "corrective", "mobility"],
    },

    // ── CONDITIONING ──────────────────────────────────────────────────────────
    {
      id: "CON-001",
      name: "Bear Crawl",
      category: "CONDITIONING",
      subcategory: "Locomotion",
      movementPattern: "Locomotion",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.82,
      sarcopeniaWeight: 0.78,
      nasmPhase: ["1","2","3"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: false,
        activationCues: ["Move silently, like a hunting panther", "Knees 1 inch off floor", "Opposite arm/leg"],
        compensationsToWatch: ["Hips rising", "Head dropping", "Breath holding"],
        inhibitTargets: [],
        activateTargets: ["Core", "Shoulders", "Hip flexors"],
      },
      equipment: ["bodyweight"],
      tags: ["functional", "athletic", "core", "locomotion"],
    },
    {
      id: "CON-002",
      name: "Burpee",
      category: "CONDITIONING",
      subcategory: "Full Body",
      movementPattern: "Locomotion",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.65,
      sarcopeniaWeight: 0.80,
      nasmPhase: ["2","3","5"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: false,
        activationCues: ["Plank position is perfect", "Explosive jump", "Soft landing"],
        compensationsToWatch: ["Sagging hips in plank", "Hard landing on knees"],
        inhibitTargets: [],
        activateTargets: ["Full body", "Core", "Glutes"],
      },
      equipment: ["bodyweight"],
      tags: ["conditioning", "full_body", "explosive", "cardio"],
    },
    {
      id: "CON-003",
      name: "Jump Squat",
      category: "CONDITIONING",
      subcategory: "Explosive Lower",
      movementPattern: "Squat",
      difficulty: "INTERMEDIATE",
      corrective: false,
      over40Suitability: 0.60,
      sarcopeniaWeight: 0.85,
      nasmPhase: ["5"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Squat depth before exploding", "Arms drive up", "Soft landing, absorb"],
        compensationsToWatch: ["Knee cave on landing", "Shallow squat", "Hard landing"],
        inhibitTargets: ["Hip flexors"],
        activateTargets: ["Glutes", "Quads", "Calves"],
      },
      equipment: ["bodyweight"],
      tags: ["explosive", "plyometric", "conditioning", "power"],
    },

    // ── RECOVERY ──────────────────────────────────────────────────────────────
    {
      id: "REC-001",
      name: "Foam Roll — IT Band",
      category: "RECOVERY",
      subcategory: "SMR",
      movementPattern: "Stability",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.99,
      sarcopeniaWeight: 0.40,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: true,
        activationCues: ["Pause on tender spots 30-90s", "Breathe through discomfort", "No rolling over joints"],
        compensationsToWatch: ["Rolling too fast", "Avoiding painful areas"],
        inhibitTargets: ["TFL", "IT Band", "Lateral quad"],
        activateTargets: [],
      },
      equipment: ["foam_roller"],
      tags: ["SMR", "recovery", "corrective", "LCS"],
    },
    {
      id: "REC-002",
      name: "Child's Pose",
      category: "RECOVERY",
      subcategory: "Passive Stretch",
      movementPattern: "Stability",
      difficulty: "BEGINNER",
      corrective: false,
      over40Suitability: 0.99,
      sarcopeniaWeight: 0.45,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: false,
        lowerCrossedRisk: false,
        activationCues: ["Breathe into low back", "Arms extended or alongside body", "Forehead to floor"],
        compensationsToWatch: ["Holding breath", "Knees not together if hip issue"],
        inhibitTargets: ["Lumbar erectors", "Hip flexors", "Lats"],
        activateTargets: [],
      },
      equipment: ["bodyweight"],
      tags: ["recovery", "flexibility", "breathing", "cool_down"],
    },
    {
      id: "REC-003",
      name: "Diaphragmatic Breathing",
      category: "RECOVERY",
      subcategory: "Nervous System",
      movementPattern: "Stability",
      difficulty: "BEGINNER",
      corrective: true,
      over40Suitability: 0.99,
      sarcopeniaWeight: 0.50,
      nasmPhase: ["1"],
      clinicalFlags: {
        upperCrossedRisk: true,
        lowerCrossedRisk: true,
        activationCues: ["Belly rises first, then chest", "4-count inhale, 6-count exhale", "Ribs expand 360°"],
        compensationsToWatch: ["Chest-only breathing", "Shoulder elevation"],
        inhibitTargets: ["Upper traps", "Scalenes", "Accessory breathing muscles"],
        activateTargets: ["Diaphragm", "Transverse abdominis", "Pelvic floor"],
      },
      equipment: ["bodyweight"],
      tags: ["nervous_system", "recovery", "corrective", "breathing", "foundation"],
    },
  ],
};
